apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-prod-us-east-1
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/nagarajurahul/gitops-platform
    targetRevision: main
    path: applicationsets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - CreateNamespace=true
